### ISSUE TITLE
Mobx based education website

### ISSUE THREAD

**Issue by tomitrescak** [mobxjs/awesome-mobx#2]
Not sure if you are interested, but I've built a platform for teaching algorithm

**Comment by tomitrescak** [comment]
Algorithmics and programming fundamentals at https://www.claraworld.net and we won several awards with it. It uses mobx and is currently being transformed to mobx state tree ;)

**Comment by hawkins** [comment]
Hey, thanks for mentioning this :smile: Sounds like a neat project!

I tried to visit the site though, and unfortunately it looks like its erroring-out when looking for `process` - are you maybe trying to run server code on the client? I wasn't able to see anything but a background image when I visited it, presumably because of this.

Unfortunately we can't take broken links, but if you could fix this up, we'd love to check it out and see if it would fit well in this list :smiley: :+1:

**Comment by tomitrescak** [comment]
Hi, I'm shocked we got 30k users on this and haven't heard this complaint. Do you have js enabled?

**Comment by tomitrescak** [comment]
I guess you gotta be patient to load 400kb of js loaded from Australian provider to load, but it still should load!! ...

**Comment by hawkins** [comment]
Yes, I do have JS enabled. It definitely was crashing on checking `process` last night, but its working fine today 👍 

I'll ping you after #3 is merged to talk about sending a PR for this to be listed as an example public project 😃

**Comment by hawkins** [comment]
@tomitrescak Just merged the new list structure - would be happy to take a PR to add Clara's World as an example project whenever you have time 👍

**Comment by tomitrescak** [comment]
Done via #11 thanks!
